<?php
/**
 * @file
 * node_json Module hooks.
 */
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_alter().
 *
 * Alter the node add/edit form 
 */

function node_json_form_alter(&$form, FormStateInterface $form_state, $form_id){
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  if($form_id == 'system_site_information_settings'){
    $form['apiKey'] = array(
      '#type'=> 'textfield',
      '#title'=> 'Enter API KEY',
      '#maxlength' => 16,
      '#size' => 16,
      '#default_value'=> $config->get('api'),
    );

    if($config->get('api') == ''){
      \Drupal::messenger()->addmessage(t('No Api key saved'),'error');
    }

    $form['#submit'][] = 'node_json_settings_submit';
  }
}
function node_json_settings_submit(&$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $config->set('api', $form_state->getValue('apiKey'));
  $config->save();
}
function node_json_uninstall() {

  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $config->clear('api')->save();
}
